# Keys should be present
["setup.cfg".flake8]
ignore__present = "str"
max-line-length__present = "int"
exclude__present = "str"
max-complexity__present = "int"
inline-quotes__present = "str"

# https://github.com/andreoliwa/nitpick/issues/271
ignore__separators = ","
exclude__separators = ","

# Keys should be absent
["setup.cfg".some-section]
ignore__present = true
max-line-length__present = true
exclude__present = true
max-complexity__present = true
inline-quotes__present = true

# Section should be absent
["setup.cfg".darglint]
__present = false
blabla = "{{ nit.section_absent() }}"

# Section should be absent
["setup.cfg"."tox:tox"]
__present = false
["setup.cfg"."gh-actions"]
__present = false

# Section should be present
["tox.ini"."tox"]
__present = true
["tox.ini".gh-actions]
__present = true

# Keys should be present using Jinja
["setup.cfg".flake8-jinja]
ignore = "{{ nit.present(str, validators=[comma_separated_str]) }}"
max-line-length = "{{ nit.present(int, validators=[range(80, 120)]) }}"
exclude = "{{ nit.present(str, validators=[comma_separated_str]) }}"
max-complexity = "{{ nit.present(int) }}"
inline-quotes = "{{ nit.present(str, choices=['double', 'single']) }}"

["setup.cfg".isort]
# https://github.com/andreoliwa/nitpick/issues/271
skip__separators = ","
known_first_party__separators = ","

["setup.cfg"."tool:pytest"]
# https://github.com/andreoliwa/nitpick/issues/271
addopts__separators = " "
norecursedirs__separators = " "
testpaths__separators = " \n"
