# Keys are absent
["pyproject.toml".tool.poetry.dev-dependencies]
pep257__present = false
pycodestyle__present = false
pur__present = false
pep257 = "{{ nit.absent() }}" # Jinja
pycodestyle = "{{ nit.absent() }}" # Jinja
pur = "{{ nit.absent() }}" # Jinja

# Keys are absent
["pyproject.toml".tool.poetry.dependencies]
pep257__present = false
pycodestyle__present = false
pur__present = false
pep257 = "{{ nit.absent() }}" # Jinja
pycodestyle = "{{ nit.absent() }}" # Jinja
pur = "{{ nit.absent() }}" # Jinja

# TODO: pre-processing with Jinja to generate multiple sections with the same config? ["pyproject.toml".tool.poetry.{{ ['dependencies', 'dev-dependencies'] }}]

# Keys are present, with the expected types
["pyproject.toml".build-system]
requires__present = "List[str]"
build-backend__present = "str"
requires = "{{ nit.present(List[str]) }}" # Jinja
build-backend = "{{ nit.present(str) }}" # Jinja

# Integer key exists
["pyproject.toml".tool.black]
line-length__present = "int"
line-length = "{{ nit.present(int) }}" # Jinja

# Section exists with anything inside
["pyproject.toml".tool.black]
__present = true
blabla = "{{ nit.section_present() }}" # Jinja
