# https://prettier.io/docs/en/configuration.html

# https://prettier.io/docs/en/options.html#print-width
printWidth = 120

# https://prettier.io/docs/en/options.html#tab-width
tabWidth = 2

# https://prettier.io/docs/en/options.html#semicolons
semi = false

# https://prettier.io/docs/en/options.html#quotes
singleQuote = false

# https://prettier.io/docs/en/options.html#trailing-commas
trailingComma = "es5"

# https://prettier.io/docs/en/options.html#end-of-line
endOfLine = "lf"
