# https://pre-commit.com/#creating-new-hooks
- id: nitpick
  name: "nitpick flake8 plugin (check files only)"
  description: "Run as a flake8 plugin and only check configuration files (TOML/INI/JSON/etc.), according to the Nitpick style"
  entry: flake8 --select=NIP
  language: python
  types: [python]
  always_run: true
  stages: [commit]

- id: nitpick-fix
  name: "nitpick fix (modify files directly)"
  description: "Fix configuration files (TOML/INI/JSON/etc.) directly, according to the Nitpick style"
  entry: nitpick fix
  language: python
  stages: [commit]

- id: nitpick-check
  name: "nitpick check (check files only)"
  description: "Only check configuration files (TOML/INI/JSON/etc.) and print the violations, according to the Nitpick style"
  entry: nitpick check
  language: python
  stages: [commit]
