# https://pre-commit.com/#creating-new-hooks
- id: nitpick
  name: "nitpick fix (auto fixing files)"
  description: "Fix configuration files (TOML/INI/JSON/etc.) directly, according to the Nitpick style"
  entry: nitpick fix
  language: python
  stages: [commit]

# This hook is kept for compatibility (or if one wants to be explicit): "nitpick" does the same as "nitpick-fix" now
- id: nitpick-fix
  name: "nitpick fix (auto fixing files)"
  description: "Fix configuration files (TOML/INI/JSON/etc.) directly, according to the Nitpick style"
  entry: nitpick fix
  language: python
  stages: [commit]

- id: nitpick-check
  name: "nitpick check (check files only)"
  description: "Only check configuration files (TOML/INI/JSON/etc.) and print the violations, according to the Nitpick style"
  entry: nitpick check
  language: python
  stages: [commit]
