# https://docs.readthedocs.io/en/stable/config-file/v2.html
# https://blog.readthedocs.com/migrate-configuration-v2/
version: 2
mkdocs:
  configuration: mkdocs.yml
formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install uv
    - uv sync --group doc
    - uv run mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
