# https://docs.readthedocs.io/en/stable/config-file/v2.html
# https://blog.readthedocs.com/migrate-configuration-v2/
version: 2
mkdocs:
  configuration: mkdocs.yml
formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    # TODO: do we still need this? Needed to force RTD to install the latest Sphinx version
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - doc
