[nitpick.meta]
name = "autoflake"
url = "https://github.com/myint/autoflake"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/myint/autoflake"

[[".pre-commit-config.yaml".repos.hooks]]
id = "autoflake"
args = ["--in-place", "--remove-all-unused-imports", "--remove-unused-variables", "--remove-duplicate-keys", "--ignore-init-module-imports"]
