[nitpick.meta]
name = "Poetry (editable projects; PEP 600 support)"
url = "https://github.com/python-poetry/poetry"

["pyproject.toml".build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"
