[nitpick.meta]
name = "Poetry"
url = "https://github.com/python-poetry/poetry"

["pyproject.toml".build-system]
# https://github.com/python-poetry/poetry/issues/1993
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
