[nitpick.meta]
name = "Read the Docs"
url = "https://github.com/readthedocs/readthedocs.org"

# https://docs.readthedocs.io/en/stable/config-file/v2.html
[".readthedocs.yaml"]
version = 2
formats = "all"

[".readthedocs.yaml".sphinx]
configuration = "docs/conf.py"

[[".readthedocs.yaml".python.install]]
method = "pip"
path = "."
extra_requirements = ["doc"]
