[nitpick.meta]
name = "SonarQube Python plugin"
url = "https://github.com/SonarSource/sonar-python"

[".codeclimate.yml".plugins.sonar-python]  # https://docs.codeclimate.com/docs/sonar-python
enabled = true
