[nitpick.meta]
name = "Commitizen (Python)"
url = "https://github.com/commitizen-tools/commitizen"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/commitizen-tools/commitizen"

[[".pre-commit-config.yaml".repos.hooks]]
id = "commitizen"
stages = ["commit-msg"]
