[nitpick.meta]
name = "commitlint"
url = "https://github.com/conventional-changelog/commitlint"

["package.json".contains_json]
commitlint = """
  {
    "extends": [
      "@commitlint/config-conventional"
    ]
  }
"""

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/alessandrojcm/commitlint-pre-commit-hook"

[[".pre-commit-config.yaml".repos.hooks]]
additional_dependencies = ["@commitlint/config-conventional"]
id = "commitlint"
stages = ["commit-msg"]
