# The values below were taken from .github/workflows/python.yaml in this repo

# 1. JMESPath as part of the section name, after the file name.
# Everything after the file name is considered a JMESPath https://jmespath.org/
# Format: ["path/to/file.ext".jmes.path.expression]
#
# 2. "jobs.build.strategy.matrix" should have "os" and "python-version"
# 3. Both are lists, and they have to be exactly as described here.
[".github/workflows/python.yaml".jobs.build.strategy.matrix]
os = ["ubuntu-latest", "macos-latest", "windows-latest"]
"python-version" = ["3.6", "3.7", "3.8", "3.9", "3.10"]

# 4. "jobs.build" should have "runs-on" with value "${{ matrix.os }}"
[".github/workflows/python.yaml".jobs.build]
"runs-on" = "${{ matrix.os }}"

# 5. "{{" and "}}" will conflict with Jinja https://github.com/andreoliwa/nitpick/issues/283
# So we need a way to turn on/off Jinja templating.
# Probably "false" will be the default, to keep compatibility.
# Whoever wants to use Jinja will need to set "true" either here or as a global config on .nitpick.toml
__jinja = false

# 6. Another way to turn off Jinja for a specific key only, not the whole dict
# (using the "__" syntax from Django filters, SQLAlchemy, factoryboy...)
"runs-on__no_jinja" = "${{ matrix.os }}"

# FIXME: create a style from this
