["pyproject.toml".tool.black]
line-length = 120

[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.0.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==19.3b0]
"""
# TODO The toml library has issues loading arrays with multiline strings:
# https://github.com/uiri/toml/issues/123
# https://github.com/uiri/toml/issues/230
# If they are fixed one day, remove this 'yaml' key and use only a 'repos' list with a single element:
#["pre-commit-config.yaml"]
#repos = ["""
#<YAML goes here>
#"""]
